apiVersion: apps/v1
kind: Deployment
metadata:
  name: drakeshop-catalog-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: drakeshop-catalog
  template:
    metadata:
      labels:
        app: drakeshop-catalog
    spec:
      containers:
      - name: drakeshop-catalog
        image: drakeshop-catalog:latest
        ports:
        - containerPort: 8082
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: "Production"
