apiVersion: apps/v1
kind: Deployment
metadata:
  name: drakeshop-identityserver-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: drakeshop-identityserver
  template:
    metadata:
      labels:
        app: drakeshop-identityserver
    spec:
      containers:
      - name: drakeshop-identityserver
        image: drakeshop-identityserver:latest
        ports:
        - containerPort: 8091
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: "Production"
